---
# tasks file for win_biztalk_2016
- name: Create biztalk artifact directory
  ansible.windows.win_file:
    path: C:\\temp\\biztalk\\
    state: directory

- name: Check if sqlxml_x64 msi exists
  ansible.builtin.win_stat:
    path: C:\\temp\\biztalk\\sqlxml_x64.msi
  register: sqlxml_status


- name: Download sqlxml_x64
  ansible.windows.win_get_url:
    url: https://download.microsoft.com/download/9/1/C/91C88B06-0922-4272-8CC1-78E445BCC8AB/sqlxml_x64.msi
    dest: C:\\temp\\biztalk\\sqlxml_x64.msi
  when: not sqlxml_status.stat.exists

- name: Install sqlxml_x64
  ansible.windows.win_package:
    path: C:\\temp\\biztalk\\sqlxml_x64.msi
    state: present