---
ansible_user: ansibleadmin
ansible_password: ""
ansible_connection: winrm
ansible_host: 40.76.78.128
ansible_winrm_port: 5985
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore

