---
- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - openjdk-17-jre
      - openjdk-17-jdk

- name: Check java version
  ansible.builtin.shell:
    cmd: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- name: Debug the java version
  debug:
    var: java_version.stdout

- name: Print a debug message
  ansible.builtin.debug:
    msg: "No change in java version"
  when: java_version.stdout == "17.0.7"
