---
# tasks file for azure_win_vm
- name: Create resource group
  azure_rm_resourcegroup:
    name: ad-test-rg
    location: eastus

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: ad-test-rg
    name: ad-test-vnet
    address_prefixes: "10.0.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: ad-test-rg
    name: ad-test-subnet
    address_prefix: "10.0.1.0/24"
    virtual_network: ad-test-vnet

- name: Create public IP address
  azure_rm_publicipaddress:
    resource_group: ad-test-rg
    allocation_method: Static
    name: ad-test-pip
  register: output_ip_address

- name: Output public IP
  debug:
    msg: "The public IP is {{ output_ip_address.state.ip_address }}"

- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: ad-test-rg
    name: ad-test-nsg
    rules:
      - name: 'allow_rdp'
        protocol: Tcp
        destination_port_range: 3389
        access: Allow
        priority: 1001
        direction: Inbound
      - name: 'allow_web_traffic'
        protocol: Tcp
        destination_port_range:
          - 80
          - 443
        access: Allow
        priority: 1002
        direction: Inbound
      - name: 'allow_powershell_remoting'
        protocol: Tcp
        destination_port_range: 
          - 5985
          - 5986
        access: Allow
        priority: 1003
        direction: Inbound

- name: Create a network interface
  azure_rm_networkinterface:
    name: nic
    resource_group: ad-test-rg
    virtual_network: ad-test-vnet
    subnet_name: ad-test-subnet
    security_group: ad-test-nsg
    ip_configurations:
      - name: default
        public_ip_address_name: ad-test-pip
        primary: True

- name: Create VM
  azure_rm_virtualmachine:
    resource_group: ad-test-rg
    name: ad-test-vm
    vm_size: Standard_B1ms
    admin_username: ansibleadmin
    admin_password: "{{ password }}"
    network_interfaces: nic
    os_type: Windows
    managed_disk_type: Standard_LRS
    image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: 2016-Datacenter
        version: latest
  no_log: false

#- name: Create VM script extension to enable HTTPS WinRM listener
#  azure_rm_virtualmachineextension:
#    name: winrm-extension
#    resource_group: ad-test-rg
#    virtual_machine_name: ad-test-vm
#    publisher: Microsoft.Compute
#    virtual_machine_extension_type: CustomScriptExtension
#    type_handler_version: '1.9'
#    settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
#    auto_upgrade_minor_version: true

- name: Get facts for one Public IP
  azure_rm_publicipaddress_info:
    resource_group: ad-test-rg
    name: ad-test-pip
  register: publicipaddresses

- name: set public ip address fact
  set_fact: publicipaddress="{{ publicipaddresses | json_query('publicipaddresses[0].ip_address')}}"

- name: wait for the WinRM port to come online
  wait_for:
    port: 5985
    host: '{{ publicipaddress }}'
    timeout: 600
