---
# tasks file for win_biztalk_2016
- name: Create biztalk artifact directory
  ansible.windows.win_file:
    path: C:\\temp\\biztalk\\
    state: directory

- name: Create biztalk install logs directory
  ansible.windows.win_file:
    path: C:\\temp\\biztalk\\logs\\
    state: directory

- name: Check if Biztalk ISO exists
  ansible.builtin.win_stat:
    path: C:\\temp\\biztalk\\BTS2016Evaluation_EN.iso
  register: biztalk_iso_status


- name: Download Biztalk Server ISO
  ansible.windows.win_get_url:
    url: https://go.microsoft.com/fwlink/p/?LinkID=2195630&clcid=0x409&culture=en-us&country=US
    dest: C:\\temp\\biztalk\\BTS2016Evaluation_EN.iso
  when: not biztalk_iso_status.stat.exists

- name: Check if Biztalk CAB file exists
  ansible.builtin.win_stat:
    path: C:\\temp\\biztalk\\BtsRedistW2K12R2EN64.cab
  register: biztalk_cab_status



- name: Download Biztalk CAB
  ansible.windows.win_get_url:
    url: https://go.microsoft.com/fwlink/p/?LinkId=746411
    dest: C:\\temp\\biztalk\\BtsRedistW2K12R2EN64.cab
  when: not biztalk_cab_status.stat.exists

- name: Create biztalk CAB artifact directory
  ansible.windows.win_file:
    path: C:\\temp\\biztalk\\cab
    state: directory

- name: Run installer from mounted Biztalk Server ISO
  ansible.windows.win_shell: expand BtsRedistW2K12R2EN64.cab -F:* C:\temp\biztalk\cab
  args:
    executable: cmd.exe
    chdir: C:\\temp\\biztalk\\

- name: Install Biztalk CAB owc11.exe
  ansible.windows.win_package:
    path: C:\\temp\\biztalk\\cab\owc11.exe
    state: present
    arguments: /q

- name: Install Biztalk CAB SQLServer2016_AS_ADOMD.msi
  ansible.windows.win_package:
    path: C:\\temp\\biztalk\\cab\SQLServer2016_AS_ADOMD.msi
    state: present

- name: Install Biztalk CAB sqlxml.msi
  ansible.windows.win_package:
    path: C:\\temp\\biztalk\\cab\sqlxml.msi
    state: present
    arguments: /q

- name: Ensure Biztalk Server ISO is mounted
  community.windows.win_disk_image:
    image_path: C:\\temp\\biztalk\\BTS2016Evaluation_EN.iso
    state: present
  register: disk_image_out
  retries: 5
  delay: 3
  until: "disk_image_out is succeeded"

- name: Print BTS2016Evaluation_EN.iso  mounted path
  ansible.builtin.debug:
    msg: "ISO Path: {{ disk_image_out.mount_paths[0] }}"

# https://learn.microsoft.com/en-us/biztalk/install-and-config-guides/appendix-a-silent-installation
#- name: Run installer from mounted Biztalk Server ISO
#  ansible.windows.win_package:
#    path: "{{ disk_image_out.mount_paths[0] }}BizTalk Server\\Setup.exe"
#    state: present
#    arguments:
#    - /QUIET
#    - /NORESTART
#    - /ADDLOCAL InfoWorkerApps,WMI,BizTalk
#    - /L C:\\temp\\biztalk\\setup_log.txt [*]
#    #- /CABPATH C:\\temp\\biztalk\\BtsRedistW2K12R2EN64.cab

- name: Run installer from mounted Biztalk Server ISO
  ansible.windows.win_shell: Setup.exe /QUIET /NORESTART /ADDLOCAL ALL /L C:\temp\biztalk\logs\setup_log.txt
  args:
    executable: cmd.exe
    chdir: "{{ disk_image_out.mount_paths[0] }}BizTalk Server\\"

- name: Unmount Biztalk Server ISO
  community.windows.win_disk_image:
    image_path: C:\\temp\\biztalk\\BTS2016Evaluation_EN.iso
    state: absent

