---
# tasks file for win_biztalk_2016

#https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170
#- name: Install Visual C++ redistributable package
#  ansible.windows.win_package:
#    path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x86.exe
#    product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
#    arguments:
#    - /install
#    #- /passive
#    - /norestart

#vcredist_x86.exe https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe

- name: Create biztalk artifact directory
  ansible.windows.win_file:
    path: C:\\temp\\biztalk\\
    state: directory

- name: Check if vcredist_x86.exe  exists
  ansible.builtin.win_stat:
    path: C:\\temp\\biztalk\\vcredist_x86.exe
  register: vcredist_status

- name: Download vcredist_x86.exe
  ansible.windows.win_get_url:
    url: https://download.microsoft.com/download/2/E/6/2E61CFA4-993B-4DD4-91DA-3737CD5CD6E3/vcredist_x86.exe
    dest: C:\\temp\\biztalk\\vcredist_x86.exe
  when: not vcredist_status.stat.exists

- name: Install vcredist_x86
  ansible.windows.win_package:
    path: C:\\temp\\biztalk\\vcredist_x86.exe
    state: present
    arguments: /q