---
# tasks file for win_biztalk_2016
#https://hahndorf.eu/blog/WindowsFeatureViaCmd
- name: Install Windows feature
  ansible.windows.win_feature:
    name:
    - Web-Server
    - Web-Common-Http
    - Web-Mgmt-Console
    - NET-Framework-Features
    state: present

#- name: Install .Net 3.5
#  ansible.windows.win_optional_feature:
#    name: NetFx3
#    state: present