---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /home/arun/anaconda3/bin/python3
  vars_prompt:
    - name: password
      prompt: "Enter local administrator password for Azure Windows VM"

  collections:
    - azure.azcollection
  roles:
    - azure_win_vm
  environment:
    AZURE_CLIENT_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    AZURE_SECRET: "{{ lookup('env', 'AZURE_SECRET') }}"
    AZURE_SUBSCRIPTION_ID: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
    AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT') }}"